site_name: Filma API Specification
site_description: Filma API 仕様書
site_url: https://docs.filma.biz/api-spec/
theme:
  name: material
  language: ja
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - search.suggest
    - search.highlight
markdown_extensions:
  - admonition
docs_dir: docs